#cloud-config
package_update: true
packages:
  - python3
  - python3-pip
  - unzip
  - wget

users:
  - name: oracle
    groups: wheel
    shell: /bin/bash
    sudo: ['ALL=(ALL) NOPASSWD:ALL']

write_files:
  - content: |
      #!/bin/bash
      set -e
      
      # Install Oracle Instant Client
      mkdir -p /opt/oracle && cd /opt/oracle
      wget -q https://download.oracle.com/otn_software/linux/instantclient/1921000/instantclient-basic-linux.x64-19.21.0.0.0dbru.zip
      unzip -q instantclient-basic-linux.x64-19.21.0.0.0dbru.zip
      
      # Set environment
      echo 'export ORACLE_HOME=/opt/oracle/instantclient_19_21' >> /etc/environment
      echo 'export LD_LIBRARY_PATH=/opt/oracle/instantclient_19_21:$LD_LIBRARY_PATH' >> /etc/environment
      echo 'export TNS_ADMIN=/home/oracle/wallet' >> /etc/environment
      
      # Oracle user environment
      mkdir -p /home/oracle/wallet
      echo 'export ORACLE_HOME=/opt/oracle/instantclient_19_21' >> /home/oracle/.bashrc
      echo 'export LD_LIBRARY_PATH=/opt/oracle/instantclient_19_21:$LD_LIBRARY_PATH' >> /home/oracle/.bashrc
      echo 'export TNS_ADMIN=/home/oracle/wallet' >> /home/oracle/.bashrc
      
      # Install Python packages
      pip3 install cx_Oracle
      
      echo "Setup completed successfully"
    path: /tmp/setup.sh
    permissions: '0755'

  - content: ${wallet_content}
    path: /tmp/wallet.b64
    encoding: b64

  - content: |
      #!/usr/bin/env python3
      import cx_Oracle
      
      def test_connection():
          try:
              wallet_dir = "/home/oracle/wallet"
              username = "ADMIN"
              password = "${admin_password}"
              service_name = "${adb_service_name}"
              
              print("Testing Oracle ADB Connection...")
              cx_Oracle.init_oracle_client(config_dir=wallet_dir)
              
              dsn = cx_Oracle.makedsn(host=None, port=None, service_name=service_name, config_dir=wallet_dir)
              connection = cx_Oracle.connect(user=username, password=password, dsn=dsn)
              
              cursor = connection.cursor()
              cursor.execute("SELECT 'Connected to Oracle ADB!' FROM dual")
              result = cursor.fetchone()
              print(f"✅ Success: {result[0]}")
              
              cursor.close()
              connection.close()
              return True
              
          except Exception as e:
              print(f"❌ Error: {e}")
              return False
      
      if __name__ == "__main__":
          test_connection()
    path: /tmp/test.py
    permissions: '0755'

  - content: |
      # Oracle ADB Environment Ready
      
      Quick test: python3 test_connection.py
      
      Connection Details:
      - Service: ${adb_service_name}
      - Wallet: /home/oracle/wallet/
      - Environment: TNS_ADMIN, ORACLE_HOME set
    path: /tmp/README.md

runcmd:
  - /tmp/setup.sh
  - base64 -d /tmp/wallet.b64 > /home/oracle/wallet/wallet.zip
  - cd /home/oracle/wallet && unzip -q wallet.zip && rm wallet.zip
  - cp /tmp/test.py /home/oracle/
  - cp /tmp/README.md /home/oracle/
  - chown -R oracle:oracle /home/oracle
  - chmod 600 /home/oracle/wallet/*
  - rm /tmp/wallet.b64

final_message: |
  Oracle ADB setup complete!
  SSH: ssh opc@<ip>
  Test: sudo su - oracle && python3 test_connection.py