title: "Oracle Autonomous Database with Python Instance"
description: "Deploy Oracle Autonomous Database (Always Free) with a Python-ready compute instance for development and learning"
informationalText: "This stack creates an Oracle Autonomous Database and a compute instance pre-configured with Python and Oracle connectivity tools. Perfect for learning and development!"
schemaVersion: 1.1.0
version: "1.0.0"
locale: "en"

variableGroups:
  - title: "Required Configuration"
    variables:
      - adb_admin_password
      - ssh_public_key

  - title: "Database Configuration"
    description: "Configure your Oracle Autonomous Database. Always Free tier provides 20GB storage and 1 OCPU forever!"
    variables:
      - use_free_tier
      - adb_cpu_core_count
      - adb_storage_size_tbs
      - adb_auto_scaling_enabled

  - title: "Compute Performance (Always Free)"
    description: "Configure your compute instance within Always Free tier limits (4 OCPU, 24GB RAM total). All options below are completely free!"
    variables:
      - preferred_shape
      - always_free_performance_tier

  - title: "Optional Configuration"
    variables:
      - environment_tag
      - project_name

variables:
  # Required Variables
  adb_admin_password:
    type: password
    title: "Database Admin Password"
    description: "Password for the Autonomous Database admin user. Must be 8+ characters with uppercase, lowercase, number and special character (e.g., Demo123!)"
    required: true
    pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^\\da-zA-Z]).{8,}$"

  ssh_public_key:
    type: ociKey
    title: "SSH Public Key"
    description: "SSH public key for accessing the compute instance"
    required: true

  # Optional Variables
  environment_tag:
    type: enum
    title: "Environment"
    description: "Environment tag for resource organization"
    default: "Demo"
    enum:
      - "Demo"
      - "Development"
      - "Testing"
      - "Learning"

  project_name:
    type: string
    title: "Project Name"
    description: "Project name for resource tagging"
    default: "Python-ADB"
    maxLength: 50

  # Database Configuration Variables
  use_free_tier:
    type: boolean
    title: "Use Always Free Database Tier"
    description: |
      🆓 **Always Free Tier Benefits:**
      - 20GB autonomous database storage
      - 1 OCPU compute
      - Automatic backups and security updates
      - **$0 cost forever!**
      
      💰 **Paid Tier Benefits:**
      - Unlimited storage and compute
      - Auto-scaling capabilities
      - Advanced features like Data Guard
      - Pay only for what you use
      
      💡 **Recommendation:** Use Always Free for demos and development, upgrade to paid for production workloads.
    default: true

  adb_cpu_core_count:
    type: number
    title: "CPU Core Count"
    description: "Number of CPU cores for ADB (ignored if using free tier)"
    default: 1
    minimum: 1
    maximum: 128
    visible: 
      not:
        - use_free_tier

  adb_storage_size_tbs:
    type: number
    title: "Storage Size (TB)"
    description: "Storage size in terabytes for ADB (ignored if using free tier)"
    default: 1
    minimum: 1
    maximum: 384
    visible: 
      not:
        - use_free_tier

  # Compute Performance Variables
  preferred_shape:
    type: enum
    title: "Compute Shape Type"
    description: |
      Choose your compute processor architecture:
      
      🔥 **ARM Shapes (Recommended for Always Free):**
      - Better power efficiency and performance per core
      - Up to 4 OCPU, 24GB RAM available for free
      
      ⚡ **x86 Shapes (Best compatibility):**
      - Native support for all x86 software and Docker images
      - No ARM translation needed
      - Flexible configurations up to 4 OCPU, 24GB RAM
      
      💡 **Quick Recommendation:**
      - **New to Oracle Cloud?** → Ampere A1 (best Always Free value)
      - **Need x86 compatibility?** → Intel E4.Flex (latest generation)
      - **Simple & reliable?** → Intel E2.1.Micro (fixed configuration)
    default: "ampere_a1"
    enum:
      - "ampere_a1"
      - "intel_e4_flex"
      - "intel_e3_flex"
      - "ampere_a2"
      - "amd_e3_flex"
      - "intel_micro"
    enumNames:
      - "🚀 Ampere A1 (ARM) - BEST Always Free performance"
      - "⚡ Intel E4.Flex (x86) - Latest Intel, full x86 compatibility"
      - "💼 Intel E3.Flex (x86) - Mature Intel, proven stability"
      - "🔄 Ampere A2 (ARM) - Alternative ARM option"
      - "🔥 AMD E3.Flex (x86) - AMD processors, good performance"
      - "🎯 Intel E2.1.Micro (x86) - Simple, fixed 1 CPU/1GB"

  always_free_performance_tier:
    type: enum
    title: "Performance Configuration"
    description: |
      Select your compute performance level:
      
      📊 **Performance Comparison:**
      - **Minimal**: 1 OCPU, 6GB RAM - Good for basic demos
      - **Balanced**: 2 OCPU, 12GB RAM - 2x faster, recommended for most use cases
      - **Maximum**: 4 OCPU, 24GB RAM - 4x faster, uses full Always Free allocation
      
      💰 **All options are completely FREE** within Oracle's Always Free tier!
      
      🎯 **Recommendation:** Start with "Balanced" for good performance, upgrade to "Maximum" if you need more power.
      
      ⚠️ **Note:** You can use up to 4 OCPU and 24GB RAM total across ALL instances in your tenancy.
    default: "balanced"
    enum:
      - "minimal"
      - "balanced"
      - "maximum"
    enumNames:
      - "💡 Minimal (1 OCPU, 6GB) - Light demos, basic testing"
      - "⚡ Balanced (2 OCPU, 12GB) - RECOMMENDED for most demos"  
      - "🚀 Maximum (4 OCPU, 24GB) - Full Always Free power!"
    visible:
      not:
        eq:
          - preferred_shape
          - "intel_micro"

outputs:
  instance_public_ip:
    title: "Instance Public IP"
    description: "Public IP address of your compute instance"
    type: link

  ssh_command:
    title: "SSH Connection Command"
    description: "Ready-to-use SSH command"
    type: copyableString

  adb_service_console_url:
    title: "Database Console"
    description: "Autonomous Database service console"
    type: link

  next_steps:
    title: "Next Steps"
    description: "Instructions for using your deployed environment"
    type: string

  cost_info:
    title: "Cost Information"
    description: "Always Free tier usage"
    type: string