title: "Simple Oracle ADB + Python Stack"
description: "Deploy Oracle Autonomous Database with Python using python-oracledb. Choose FREE or PAID resources."
informationalText: "✅ Always Free tier selected by default ($0 cost). Uncheck for paid resources with custom sizing."
schemaVersion: 1.1.0
version: "1.0"
locale: "en"

variableGroups:
  - title: "🔑 Required Information"
    visible: true
    variables:
      - ssh_public_key
      - admin_password

  - title: "⚙️ Deployment Mode"
    visible: true
    variables:
      - use_free_tier

  - title: "📝 Basic Settings"
    visible: true
    variables:
      - project_name
      - database_name

  - title: "💰 Paid Tier Configuration"
    visible:
      not:
        - ${use_free_tier}
    variables:
      - compute_ocpus
      - compute_memory_gb
      - adb_cpu_cores
      - adb_storage_gb
      - enable_auto_scaling

variables:
  # Hide auto-provided variables
  compartment_ocid:
    type: string
    visible: false
    required: false

  tenancy_ocid:
    type: string
    visible: false
    required: false

  region:
    type: string
    visible: false
    required: false

  # Required inputs
  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "SSH Public Key"
    description: "Your SSH public key to access the compute instance"
    required: true

  admin_password:
    type: password
    title: "Admin Password"
    description: "Password for database ADMIN user (8+ characters)"
    required: true
    minLength: 8
    maxLength: 30

  # Deployment mode
  use_free_tier:
    type: boolean
    title: "✅ Use Always Free Resources"
    description: "Keep CHECKED for free resources ($0/month). UNCHECK for paid resources with custom sizing."
    default: true

  # Basic settings
  project_name:
    type: string
    title: "Project Name"
    description: "Name prefix for all resources"
    default: "python-oracle"
    pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
    maxLength: 20

  database_name:
    type: string
    title: "Database Name"
    description: "Autonomous Database name"
    default: "PYTHONDB"
    pattern: "^[A-Za-z][A-Za-z0-9]*$"
    maxLength: 14

  # Paid tier configuration
  compute_ocpus:
    type: number
    title: "Compute OCPUs"
    description: "Number of OCPUs for compute instance"
    default: 2
    minimum: 1
    maximum: 32

  compute_memory_gb:
    type: number
    title: "Compute Memory (GB)"
    description: "Memory in GB for compute instance"
    default: 16
    minimum: 1
    maximum: 512

  adb_cpu_cores:
    type: number
    title: "Database CPU Cores"
    description: "Number of CPU cores for Autonomous Database"
    default: 2
    minimum: 1
    maximum: 128

  adb_storage_gb:
    type: number
    title: "Database Storage (GB)"
    description: "Storage in GB for Autonomous Database"
    default: 1024
    minimum: 20
    maximum: 393216

  enable_auto_scaling:
    type: boolean
    title: "Enable Auto Scaling"
    description: "Enable auto-scaling for the database"
    default: false

outputGroups:
  - title: "🔗 Connection"
    outputs:
      - instance_ip
      - ssh_command
      - connection_strings

  - title: "📊 Summary"
    outputs:
      - deployment_summary

  - title: "🚀 Get Started"
    outputs:
      - next_steps