title: "Oracle ADB + Python"
stackDescription: "Minimal Oracle Autonomous Database with Python setup"
schemaVersion: "1.1.0"
version: "20250630"
locale: "en"

variableGroups:
  - title: "Required Configuration"
    variables:
      - admin_password
      - ssh_public_key

variables:
  tenancy_ocid:
    type: string
    required: true
    visible: false

  region:
    type: oci:identity:region:name
    required: true
    visible: false

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visible: false

  admin_password:
    type: password
    required: true
    title: "Database Admin Password"
    description: "Password for ADMIN user (8+ characters)"
    minLength: 8
    maxLength: 30

  ssh_public_key:
    type: oci:core:ssh:publickey
    required: true
    title: "SSH Public Key"
    description: "SSH public key for instance access"

  instance_shape:
    type: oci:core:instanceshape:name
    required: true
    default: "VM.Standard.E2.1.Micro"
    title: "Instance Shape"
    dependsOn:
      compartmentId: ${compartment_ocid}

outputs:
  database_id:
    title: "Database OCID"
    type: ocid

  instance_ip:
    title: "Instance IP"
    type: string

  ssh_command:
    title: "SSH Command"
    type: string

  setup_instructions:
    title: "Setup Instructions"
    type: string