title: "Oracle Autonomous Database with Python Instance"
description: "Deploy Oracle Autonomous Database (Always Free) with a Python-ready compute instance for development and learning"
informationalText: "This stack creates an Oracle Autonomous Database and a compute instance pre-configured with Python and Oracle connectivity tools. Perfect for learning and development!"
schemaVersion: 1.1.0
version: "1.0.0"
locale: "en"

variableGroups:
  - title: "Required Configuration"
    variables:
      - adb_admin_password
      - ssh_public_key

  - title: "Database Configuration"
    variables:
      - use_free_tier
      - adb_cpu_core_count
      - adb_storage_size_tbs
      - adb_auto_scaling_enabled

  - title: "Compute Performance (Always Free)"
    variables:
      - preferred_shape
      - always_free_performance_tier

  - title: "Optional Configuration"
    variables:
      - environment_tag
      - project_name

variables:
  # Required Variables
  adb_admin_password:
    type: password
    title: "Database Admin Password"
    description: "Password for the Autonomous Database admin user. Must be 8+ characters with uppercase, lowercase, number and special character (e.g., Demo123!)"
    required: true
    pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^\\da-zA-Z]).{8,}$"

  ssh_public_key:
    type: ociKey
    title: "SSH Public Key"
    description: "SSH public key for accessing the compute instance"
    required: true

  # Optional Variables
  environment_tag:
    type: enum
    title: "Environment"
    description: "Environment tag for resource organization"
    default: "Demo"
    enum:
      - "Demo"
      - "Development"
      - "Testing"
      - "Learning"

  project_name:
    type: string
    title: "Project Name"
    description: "Project name for resource tagging"
    default: "Python-ADB"
    maxLength: 50

  # Database Configuration Variables
  use_free_tier:
    type: boolean
    title: "Use Always Free Tier"
    description: "Enable to use Always Free tier (if available), disable for paid tier"
    default: false

  adb_cpu_core_count:
    type: number
    title: "CPU Core Count"
    description: "Number of CPU cores for ADB (ignored if using free tier)"
    default: 1
    minimum: 1
    maximum: 128
    visible: 
      not:
        - use_free_tier

  adb_storage_size_tbs:
    type: number
    title: "Storage Size (TB)"
    description: "Storage size in terabytes for ADB (ignored if using free tier)"
    default: 1
    minimum: 1
    maximum: 384
    visible: 
      not:
        - use_free_tier

  # Compute Performance Variables
  preferred_shape:
    type: enum
    title: "Compute Shape Type"
    description: "Select compute shape family (Ampere shapes support flexible CPU/memory)"
    default: "ampere_a1"
    enum:
      - value: "ampere_a1"
        displayName: "Ampere A1 (ARM) - Best flexibility"
      - value: "intel_micro" 
        displayName: "Intel E2.1.Micro - Fixed 1 CPU, 1GB"
      - value: "ampere_a2"
        displayName: "Ampere A2 (ARM) - Regional availability"

  always_free_performance_tier:
    type: enum
    title: "Always Free Performance Level"
    description: "Choose your performance tier (all options are free within 4 OCPU limit)"
    default: "balanced"
    enum:
      - value: "minimal"
        displayName: "Minimal (1 OCPU, 6GB) - Basic demos"
      - value: "balanced"
        displayName: "Balanced (2 OCPU, 12GB) - Recommended"  
      - value: "maximum"
        displayName: "Maximum (4 OCPU, 24GB) - Full Always Free"
    visible:
      or:
        - eq:
          - preferred_shape
          - "ampere_a1"
        - eq:
          - preferred_shape  
          - "ampere_a2"

outputs:
  instance_public_ip:
    title: "Instance Public IP"
    description: "Public IP address of your compute instance"
    type: link

  ssh_command:
    title: "SSH Connection Command"
    description: "Ready-to-use SSH command"
    type: copyableString

  adb_service_console_url:
    title: "Database Console"
    description: "Autonomous Database service console"
    type: link

  next_steps:
    title: "Next Steps"
    description: "Instructions for using your deployed environment"
    type: string

  cost_info:
    title: "Cost Information"
    description: "Always Free tier usage"
    type: string