title: "Oracle Autonomous Database + Python Stack"
description: "Deploy Oracle Autonomous Database with Python-ready compute instance. Toggle between Always Free and paid tiers."
informationalText: "This stack deploys a complete Python development environment with Oracle Autonomous Database. Use Always Free tier for development or paid tier for production workloads."
schemaVersion: 1.1.0
version: "2.0"
locale: "en"

# Variable Groups for better UI organization
variableGroups:
  - title: "Required Configuration"
    visible: true
    variables:
      - compartment_id
      - ssh_public_key
      - db_admin_password

  - title: "Deployment Options"
    visible: true
    variables:
      - use_free_tier
      - resource_prefix
      - db_name

  - title: "Compute Configuration (Paid Tier)"
    visible:
      not:
        - ${use_free_tier}
    variables:
      - instance_shape
      - instance_ocpus
      - instance_memory_gb

  - title: "Database Configuration (Paid Tier)"
    visible:
      not:
        - ${use_free_tier}
    variables:
      - adb_cpu_core_count
      - adb_storage_tb
      - adb_auto_scaling
      - adb_backup_retention_days

  - title: "Advanced Options"
    visible: true
    variables:
      - enable_web_ports
      - adb_version
      - adb_license_model
      - adb_workload

# Variable Definitions
variables:
  # Required Configuration
  compartment_id:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "Choose the compartment where all resources will be created"
    required: true

  ssh_public_key:
    type: oci:core:ssh:publickey
    title: "SSH Public Key"
    description: "Paste your SSH public key to access the compute instance"
    required: true
    additionalProps:
      allowMultiple: false

  db_admin_password:
    type: password
    title: "Database Admin Password"
    description: "Password for the ADMIN user (8+ characters, include uppercase, lowercase, number)"
    required: true
    minLength: 8
    maxLength: 30
    pattern: "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d).*$"

  # Deployment Options
  use_free_tier:
    type: boolean
    title: "Use Always Free Tier"
    description: "Enable to use Always Free resources (recommended for development)"
    default: true

  resource_prefix:
    type: string
    title: "Resource Name Prefix"
    description: "Prefix for all resource names"
    default: "python-oracle"
    pattern: "^[a-zA-Z][a-zA-Z0-9-]*$"
    maxLength: 20

  db_name:
    type: string
    title: "Database Name"
    description: "Name for the Autonomous Database (alphanumeric only, max 14 characters)"
    default: "PYTHONADB"
    pattern: "^[A-Za-z][A-Za-z0-9]*$"
    maxLength: 14

  # Compute Configuration (Paid Tier)
  instance_shape:
    type: enum
    title: "Instance Shape"
    description: "Compute instance shape for paid tier"
    default: "VM.Standard.E4.Flex"
    enum:
      - "VM.Standard.E3.Flex"
      - "VM.Standard.E4.Flex"
      - "VM.Standard.A1.Flex"
      - "VM.Standard3.Flex"

  instance_ocpus:
    type: number
    title: "Instance OCPUs"
    description: "Number of OCPUs for the compute instance"
    default: 2
    minimum: 1
    maximum: 64

  instance_memory_gb:
    type: number
    title: "Instance Memory (GB)"
    description: "Amount of memory in GB"
    default: 16
    minimum: 1
    maximum: 1024

  # Database Configuration (Paid Tier)
  adb_cpu_core_count:
    type: number
    title: "Database CPU Cores"
    description: "Number of CPU cores for Autonomous Database"
    default: 2
    minimum: 1
    maximum: 128

  adb_storage_tb:
    type: number
    title: "Database Storage (TB)"
    description: "Storage size in terabytes"
    default: 1
    minimum: 1
    maximum: 384

  adb_auto_scaling:
    type: boolean
    title: "Enable Auto Scaling"
    description: "Automatically scale CPU based on workload"
    default: false

  adb_backup_retention_days:
    type: number
    title: "Backup Retention (Days)"
    description: "Number of days to retain automatic backups"
    default: 7
    minimum: 1
    maximum: 60

  # Advanced Options
  enable_web_ports:
    type: boolean
    title: "Enable Web Ports"
    description: "Open HTTP (80) and HTTPS (443) ports for web applications"
    default: false

  adb_version:
    type: enum
    title: "Database Version"
    description: "Oracle Database version"
    default: "19c"
    enum:
      - "19c"
      - "21c"
      - "23ai"

  adb_license_model:
    type: enum
    title: "License Model"
    description: "Database license model"
    default: "LICENSE_INCLUDED"
    enum:
      - "LICENSE_INCLUDED"
      - "BRING_YOUR_OWN_LICENSE"

  adb_workload:
    type: enum
    title: "Workload Type"
    description: "Type of database workload"
    default: "OLTP"
    enum:
      - "OLTP"
      - "DW"
      - "AJD"

# Output Groups
outputGroups:
  - title: "Connection Information"
    outputs:
      - instance_public_ip
      - ssh_connection_command
      - database_connection_strings

  - title: "Resource Details"
    outputs:
      - deployment_mode
      - resource_summary
      - autonomous_database_id

  - title: "Getting Started"
    outputs:
      - quick_start_instructions